name: Build docker image

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string

env:
  ENVIRONMENT_NAME: ${{ inputs.environment-name }}

  REGISTRY: ghcr.io
  REGISTRY_USER: xloo
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_docker_image:
    runs-on: [self-hosted]
    name: Build & deploy docker image
    environment:
      name: ${{ inputs.environment-name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up environment variables
        run: |
          export CI_COMMIT_REF_SHORT=${GITHUB_REF##*/}
          export CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SHORT//./_}
          echo "CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}" >> $GITHUB_ENV
          export CI_PROJECT_NAME=${GITHUB_REPOSITORY##*/}
          echo "CI_PROJECT_NAME=${CI_PROJECT_NAME//_/-}" >> $GITHUB_ENV
          echo "CI_REGISTRY_IMAGE=${{ env.REGISTRY }}/autoxloo/${GITHUB_REPOSITORY##*/}:${CI_COMMIT_REF_SHORT//./_}" >> $GITHUB_ENV

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

       # Pull Docker image:
      - name: Pull previous image
        run: |
           echo "docker image pull $CI_REGISTRY_IMAGE"
           docker image pull $CI_REGISTRY_IMAGE || true

      - name: Build image
        run: |
           echo "docker build -f .deploy/Dockerfile -t "${CI_REGISTRY_IMAGE}" --cache-from="${CI_REGISTRY_IMAGE}" ."
           docker build -f .deploy/Dockerfile -t "${CI_REGISTRY_IMAGE}" --cache-from="${CI_REGISTRY_IMAGE}" .

       # Publish image to github package repository:
      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: |
           echo "docker push '${CI_REGISTRY_IMAGE}'"
           docker push "${CI_REGISTRY_IMAGE}"
